fun main(){
    val humano = Human()
    println("Humano")
    println("Vive na terra: ${humano.walkOnEath()}")
    println("Sabe nadar: ${humano.canSwin()}")
    println("Sabe voar: ${humano.canFly()}")
    println("Está viva: ${humano.isAlive()}")
    println("Bota ovos: ${humano.layEggs()}")
    println()

    val einstein = Einstein()
    println("Albert Eistein")
    println("Vive na terra: ${einstein.walkOnEath()}")
    println("Sabe nadar: ${einstein.canSwin()}")
    println("Sabe voar: ${einstein.canFly()}")
    println("Está viva: ${einstein.isAlive()}")
    println("Bota ovos: ${einstein.layEggs()}")
    println()

    val hawk = Hawk()
    println("Falcão")
    println("Vive na terra: ${hawk.walkOnEath()}")
    println("Sabe nadar: ${hawk.canSwin()}")
    println("Sabe voar: ${hawk.canFly()}")
    println("Está viva: ${hawk.isAlive()}")
    println("Bota ovos: ${hawk.layEggs()}")
    println()

    val snake = Snake()
    println("Cobra")
    println("Vive na terra: ${snake.walkOnEath()}")
    println("Sabe nadar: ${snake.canSwin()}")
    println("Sabe voar: ${snake.canFly()}")
    println("Está viva: ${snake.isAlive()}")
    println("Bota ovos: ${snake.layEggs()}")
    println()

    val dog = Dog()
    println("Cachorro")
    println("Vive na terra: ${dog.walkOnEath()}")
    println("Sabe nadar: ${dog.canSwin()}")
    println("Sabe voar: ${dog.canFly()}")
    println("Está viva: ${dog.isAlive()}")
    println("Bota ovos: ${dog.layEggs()}")
    println()

    val whale = Whale()
    println("Baleia Baleia")
    println("Vive na terra: ${whale.walkOnEath()}")
    println("Sabe nadar: ${whale.canSwin()}")
    println("Sabe voar: ${whale.canFly()}")
    println("Está viva: ${whale.isAlive()}")
    println("Bota ovos: ${whale.layEggs()}")
    println()

    val penguim = Penguim()
    println("Pinguins")
    println("Vive na terra: ${penguim.walkOnEath()}")
    println("Sabe nadar: ${penguim.canSwin()}")
    println("Sabe voar: ${penguim.canFly()}")
    println("Está viva: ${penguim.isAlive()}")
    println("Bota ovos: ${penguim.layEggs()}")
    println()

    val bat = Bat()
    println("Morcego")
    println("Vive na terra: ${bat.walkOnEath()}")
    println("Sabe nadar: ${bat.canSwin()}")
    println("Sabe voar: ${bat.canFly()}")
    println("Está viva: ${bat.isAlive()}")
    println("Bota ovos: ${bat.layEggs()}")
    println()

    val platypus = Platypus()
    println("Perry, o Ornitorrinco")
    println("Vive na terra: ${platypus.walkOnEath()}")
    println("Sabe nadar: ${platypus.canSwin()}")
    println("Sabe voar: ${platypus.canFly()}")
    println("Está viva: ${platypus.isAlive()}")
    println("Bota ovos: ${platypus.layEggs()}")
    println()

}